### ISSUE TITLE
code of conduct?

### ISSUE THREAD

**Issue by Pushplaybang** [Nona-Creative/github-boilerplate#6]
Found this, http://contributor-covenant.org/version/1/4/

thought it was interesting,  - what are your thoughts? @Nona-Creative/nonabots

**Comment by Pushplaybang** [comment]
@darrynten @royscheeren @RollYourOwnEd @ShaunEgan @SkippyZA @JamesGarethSmith @slopboy @leogopal   - Any thoughts?

**Comment by ShaunEgan** [comment]
Seems cool - will probably need some changes to make it appropriate here, but the overall the document seems good.

**Comment by Pushplaybang** [comment]
@ShaunEgan  - Yeah I think its a cool idea, we can use it as a starter.

**Comment by JamesGarethSmith** [comment]
:+1:
